version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/dellee

hooks:
  ApplicationStop:
    - location: deploy/application_stop.sh
      timeout: 300
      runas: root

  # AfterInstall:
  #   - location: deploy/after_install.sh
  #     timeout: 600
  #     runas: ubuntu

  ApplicationStart:
    - location: deploy/application_start.sh
      timeout: 300
      runas: root
